import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TransPay</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo.jpg' />
      </Head>
      <Hero heading='Capture Photography' message='I capture moments in nature and keep them alive.'/>
    </div>
  )
}

export default Home
